/*     */ package org.nyxiikcz.aioptimizer.systems;
/*     */ 
/*     */ import com.sun.net.httpserver.HttpExchange;
/*     */ import com.sun.net.httpserver.HttpHandler;
/*     */ import java.io.OutputStream;
/*     */ import java.nio.charset.StandardCharsets;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ class RootHandler
/*     */   implements HttpHandler
/*     */ {
/*     */   private final WebServerManager manager;
/*     */   
/*     */   public RootHandler(WebServerManager paramWebServerManager) {
/* 199 */     this.manager = paramWebServerManager;
/*     */   }
/*     */   
/*     */   public void handle(HttpExchange paramHttpExchange) {
/*     */     String str;
/* 204 */     if (!this.manager.isAuthenticated(paramHttpExchange)) {
/* 205 */       str = "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>AI Optimizer | Login</title>\n    <style>\n        body { background: #0f172a; font-family: 'Segoe UI', system-ui, sans-serif; display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; color: #fff; }\n        .bg-shapes { position: absolute; top: 0; left: 0; width: 100%; height: 100%; z-index: -1; overflow: hidden; }\n        .shape { position: absolute; background: #1e3a8a; filter: blur(80px); border-radius: 50%; opacity: 0.5; }\n        .s1 { width: 400px; height: 400px; top: -100px; left: -100px; } .s2 { width: 500px; height: 500px; bottom: -150px; right: -100px; background: #3b82f6; }\n        .login-card { background: #1e293b; padding: 2.5rem 2rem; border-radius: 1rem; box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.5); width: 100%; max-width: 380px; text-align: center; border: 1px solid #334155; z-index: 1; }\n        .login-card h2 { margin-top: 0; color: #3b82f6; font-size: 2rem; margin-bottom: 2rem; }\n        .input-group { margin-bottom: 1.25rem; text-align: left; position: relative; }\n        .input-group label { display: block; font-size: 0.85rem; color: #94a3b8; margin-bottom: 0.5rem; font-weight: 600; }\n        .input-group input { width: 100%; padding: 0.85rem; border-radius: 0.5rem; border: 1px solid #334155; background: #0f172a; color: white; outline: none; box-sizing: border-box; font-size: 1rem; transition: 0.2s; }\n        .input-group input:focus { border-color: #3b82f6; box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.2); }\n        .btn-login { width: 100%; padding: 0.85rem; background: #3b82f6; color: white; font-weight: bold; border: none; border-radius: 0.5rem; cursor: pointer; transition: 0.2s; font-size: 1.1rem; margin-top: 1rem; }\n        .btn-login:hover { background: #2563eb; transform: translateY(-2px); }\n        .error-msg { background: rgba(239, 68, 68, 0.1); color: #ef4444; padding: 0.75rem; border-radius: 0.5rem; font-size: 0.9rem; margin-bottom: 1.5rem; border: 1px solid rgba(239, 68, 68, 0.2); display: none; }\n    </style>\n</head>\n<body>\n    <div class=\"bg-shapes\"><div class=\"shape s1\"></div><div class=\"shape s2\"></div></div>\n    <div class=\"login-card\">\n        <h2>🤖 AI Optimizer</h2>\n        <div class=\"error-msg\" id=\"err\">Invalid username or password!</div>\n        <div class=\"input-group\">\n            <label>Username</label>\n            <input type=\"text\" id=\"user\" placeholder=\"Enter username\">\n        </div>\n        <div class=\"input-group\">\n            <label>Password</label>\n            <input type=\"password\" id=\"pass\" placeholder=\"Enter password\" onkeypress=\"handleEnter(event)\">\n        </div>\n        <button class=\"btn-login\" onclick=\"doLogin()\">Login</button>\n    </div>\n    <script>\n        function handleEnter(e) { if(e.key === 'Enter') doLogin(); }\n        function doLogin() {\n            const u = document.getElementById('user').value;\n            const p = document.getElementById('pass').value;\n            fetch('/api/login', { method: 'POST', body: JSON.stringify({u: u, p: p}) })\n            .then(r => r.json()).then(res => {\n                if(res.success) window.location.reload();\n                else { document.getElementById('err').style.display = 'block'; }\n            }).catch(() => document.getElementById('err').style.display = 'block');\n        }\n    </script>\n</body>\n</html>";
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */     
/*     */     }
/*     */     else {
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */       
/* 257 */       str = "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>AI Optimizer | Admin Panel</title>\n    <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\n    <style>\n        :root { --bg: #0f172a; --sidebar: #1e293b; --card: #1e293b; --text: #f8fafc; --text-muted: #94a3b8; --accent: #3b82f6; --accent-hover: #2563eb; --success: #10b981; --warn: #f59e0b; --danger: #ef4444; --border: #334155; }\n        * { box-sizing: border-box; }\n        body { background: var(--bg); color: var(--text); font-family: 'Segoe UI', system-ui, sans-serif; margin: 0; display: flex; height: 100vh; overflow: hidden; }\n        .sidebar { width: 260px; background: var(--sidebar); border-right: 1px solid var(--border); display: flex; flex-direction: column; }\n        .sidebar-header { padding: 1.5rem; font-size: 1.5rem; font-weight: 700; color: var(--accent); border-bottom: 1px solid var(--border); display: flex; align-items: center; gap: 10px; }\n        .nav-menu { padding: 1rem 0; flex-grow: 1; }\n        .nav-item { padding: 1rem 1.5rem; color: var(--text-muted); cursor: pointer; transition: 0.2s; display: flex; align-items: center; gap: 12px; font-weight: 500; }\n        .nav-item:hover { background: rgba(59, 130, 246, 0.1); color: var(--text); }\n        .nav-item.active { border-left: 4px solid var(--accent); background: rgba(59, 130, 246, 0.15); color: var(--text); }\n        .main-content { flex-grow: 1; padding: 2rem; overflow-y: auto; }\n        .top-bar { display: flex; justify-content: space-between; align-items: center; margin-bottom: 2rem; }\n        .page-title { font-size: 1.8rem; font-weight: 700; }\n        .live-badge { display: flex; align-items: center; gap: 0.5rem; background: rgba(16, 185, 129, 0.1); color: var(--success); padding: 0.4rem 1rem; border-radius: 9999px; font-weight: 600; font-size: 0.875rem; border: 1px solid rgba(16, 185, 129, 0.2); }\n        .dot { width: 8px; height: 8px; background: var(--success); border-radius: 50%; animation: pulse 2s infinite; }\n        .view { display: none; animation: fadeIn 0.3s; }\n        .view.active { display: block; }\n        .sub-nav { display: flex; gap: 10px; margin-bottom: 20px; border-bottom: 2px solid var(--border); padding-bottom: 15px; }\n        .sub-tab { background: var(--card); border: 1px solid var(--border); color: var(--text-muted); padding: 10px 20px; cursor: pointer; font-weight: 600; border-radius: 8px; transition: 0.2s; }\n        .sub-tab:hover { border-color: var(--accent); color: var(--text); }\n        .sub-tab.active { background: var(--accent); color: white; border-color: var(--accent); }\n        .chart-sub-container { display: none; animation: fadeIn 0.3s; }\n        .chart-sub-container.active { display: block; }\n        @keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }\n        .status-banner { text-align: center; padding: 1.5rem; border-radius: 0.75rem; font-size: 1.25rem; font-weight: 700; margin-bottom: 2rem; transition: 0.3s; }\n        .STABLE { background: rgba(16, 185, 129, 0.1); color: var(--success); border: 1px solid rgba(16, 185, 129, 0.2); }\n        .MILD_LOAD { background: rgba(245, 158, 11, 0.1); color: var(--warn); border: 1px solid rgba(245, 158, 11, 0.2); }\n        .HIGH_LOAD { background: rgba(239, 68, 68, 0.1); color: var(--danger); border: 1px solid rgba(239, 68, 68, 0.2); }\n        .CRITICAL { background: rgba(239, 68, 68, 0.2); color: #fca5a5; border: 1px solid var(--danger); animation: danger-pulse 1.5s infinite; }\n        .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 1.25rem; margin-bottom: 1.25rem; }\n        .card { background: var(--card); padding: 1.5rem; border-radius: 0.75rem; border: 1px solid var(--border); }\n        .card-header { font-size: 0.875rem; font-weight: 600; color: var(--text-muted); text-transform: uppercase; margin-bottom: 0.5rem; }\n        .card-value { font-size: 2.25rem; font-weight: 700; }\n        .val-good { color: var(--success); } .val-warn { color: var(--warn); } .val-bad { color: var(--danger); }\n        .btn { padding: 1rem 1.5rem; border-radius: 0.5rem; border: none; font-size: 1rem; font-weight: 600; cursor: pointer; transition: 0.2s; color: white; }\n        .btn-danger { background: var(--danger); } .btn-danger:hover { background: #b91c1c; }\n        .btn-warn { background: var(--warn); color: #000; } .btn-warn:hover { background: #d97706; }\n        .btn-primary { background: var(--accent); } .btn-primary:hover { background: var(--accent-hover); }\n        .stat-group { background: rgba(30, 41, 59, 0.5); padding: 1.25rem; border-radius: 0.75rem; border: 1px solid var(--border); }\n        .stat-group-title { font-size: 0.85rem; color: var(--text-muted); text-transform: uppercase; font-weight: 700; border-bottom: 1px solid var(--border); padding-bottom: 0.75rem; margin-bottom: 0.75rem; }\n        .stat-row { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem; font-size: 0.95rem; }\n        .stat-label { color: #cbd5e1; font-weight: 500; }\n        .stat-val { font-weight: 700; }\n        .player-card { display: flex; align-items: center; justify-content: space-between; background: rgba(30, 41, 59, 0.8); padding: 1rem; border-radius: 0.5rem; border: 1px solid var(--border); }\n        .player-info { display: flex; align-items: center; gap: 15px; }\n        .player-head { width: 40px; height: 40px; border-radius: 4px; }\n        .chunk-table { width: 100%; border-collapse: collapse; margin-top: 10px; }\n        .chunk-table th, .chunk-table td { padding: 10px; text-align: left; border-bottom: 1px solid var(--border); }\n        .chunk-table th { color: var(--text-muted); text-transform: uppercase; font-size: 0.8rem; }\n        @keyframes pulse { 0% { opacity: 1; transform: scale(1); } 50% { opacity: 0.5; transform: scale(1.2); } 100% { opacity: 1; transform: scale(1); } }\n        @keyframes danger-pulse { 0% { box-shadow: 0 0 0 0 rgba(239, 68, 68, 0.4); } 70% { box-shadow: 0 0 0 10px rgba(239, 68, 68, 0); } 100% { box-shadow: 0 0 0 0 rgba(239, 68, 68, 0); } }\n    </style>\n</head>\n<body>\n    <aside class=\"sidebar\">\n        <div class=\"sidebar-header\">🤖 AI Optimizer</div>\n        <div class=\"nav-menu\">\n            <div class=\"nav-item active\" onclick=\"switchTab('overview')\" id=\"nav-overview\">📊 Dashboard</div>\n            <div class=\"nav-item\" onclick=\"switchTab('charts')\" id=\"nav-charts\">📈 Charts</div>\n            <div class=\"nav-item\" onclick=\"switchTab('playersList')\" id=\"nav-playersList\">👥 Players List</div>\n            <div class=\"nav-item\" onclick=\"switchTab('actions')\" id=\"nav-actions\">⚡ Action Center</div>\n        </div>\n    </aside>\n    <main class=\"main-content\">\n        <div class=\"top-bar\">\n            <div class=\"page-title\" id=\"page-title\">Dashboard Overview</div>\n            <div class=\"live-badge\"><div class=\"dot\"></div>LIVE SERVER</div>\n        </div>\n        <div id=\"status-banner\" class=\"status-banner STABLE\">CONNECTING TO SERVER...</div>\n        \n        \n        <div id=\"view-overview\" class=\"view active\">\n            <div class=\"grid\">\n                <div class=\"card\"><div class=\"card-header\">Server TPS</div><div id=\"val-tps\" class=\"card-value\">--</div></div>\n                <div class=\"card\"><div class=\"card-header\">Tick Duration (MSPT)</div><div id=\"val-mspt\" class=\"card-value\">--</div></div>\n                <div class=\"card\"><div class=\"card-header\">CPU Usage</div><div id=\"val-cpu\" class=\"card-value\">--</div></div>\n                <div class=\"card\"><div class=\"card-header\">RAM Usage</div><div id=\"val-ram\" class=\"card-value\">--</div></div>\n                <div class=\"card\"><div class=\"card-header\">Disk (SSD)</div><div id=\"val-disk\" class=\"card-value\">--</div></div>\n            </div>\n            <div class=\"grid\">\n                <div class=\"card\"><div class=\"card-header\">AI Stress Score</div><div id=\"val-stress\" class=\"card-value\">--</div></div>\n                <div class=\"card\"><div class=\"card-header\">Loaded Chunks</div><div id=\"val-chunks\" class=\"card-value\">--</div></div>\n                <div class=\"card\"><div class=\"card-header\">Tracked Entities</div><div id=\"val-entities\" class=\"card-value\">--</div></div>\n                <div class=\"card\"><div class=\"card-header\">Online Players</div><div id=\"val-players\" class=\"card-value\" style=\"color: var(--accent);\">-- / --</div></div>\n            </div>\n        </div>\n\n        \n        <div id=\"view-charts\" class=\"view\">\n            <div class=\"sub-nav\">\n                <button class=\"sub-tab active\" onclick=\"switchSubTab('perf')\" id=\"sub-tab-perf\">⚡ Performance</button>\n                <button class=\"sub-tab\" onclick=\"switchSubTab('world')\" id=\"sub-tab-world\">🌍 World Data</button>\n                <button class=\"sub-tab\" onclick=\"switchSubTab('players')\" id=\"sub-tab-players\">👥 Players (History)</button>\n            </div>\n            \n            <div id=\"sub-view-perf\" class=\"chart-sub-container active\">\n                <div class=\"grid\" style=\"grid-template-columns: 1fr;\">\n                    <div class=\"card\"><div class=\"card-header\">TPS & MSPT (24h)</div><div style=\"height: 300px;\"><canvas id=\"perfChart\"></canvas></div></div>\n                    <div class=\"card\"><div class=\"card-header\">System Resources (CPU & RAM)</div><div style=\"height: 300px;\"><canvas id=\"sysChart\"></canvas></div></div>\n                    <div class=\"card\"><div class=\"card-header\">Storage Drive (SSD/HDD) Usage</div><div style=\"height: 300px;\"><canvas id=\"diskChart\"></canvas></div></div>\n                </div>\n                <div class=\"grid\" style=\"grid-template-columns: repeat(5, 1fr); margin-top: 1rem;\">\n                    <div class=\"stat-group\">\n                        <div class=\"stat-group-title\">⚡ TPS</div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Current:</span><span id=\"stat-curr-tps\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Average:</span><span id=\"stat-avg-tps\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Lowest:</span><span id=\"stat-min-tps\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Peak:</span><span id=\"stat-max-tps\" class=\"stat-val\">--</span></div>\n                    </div>\n                    <div class=\"stat-group\">\n                        <div class=\"stat-group-title\">⏱️ MSPT</div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Current:</span><span id=\"stat-curr-mspt\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Average:</span><span id=\"stat-avg-mspt\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Lowest:</span><span id=\"stat-min-mspt\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Peak:</span><span id=\"stat-max-mspt\" class=\"stat-val\">--</span></div>\n                    </div>\n                    <div class=\"stat-group\">\n                        <div class=\"stat-group-title\">💻 CPU</div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Current:</span><span id=\"stat-curr-cpu\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Average:</span><span id=\"stat-avg-cpu\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Lowest:</span><span id=\"stat-min-cpu\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Peak:</span><span id=\"stat-max-cpu\" class=\"stat-val\">--</span></div>\n                    </div>\n                    <div class=\"stat-group\">\n                        <div class=\"stat-group-title\">🧠 RAM</div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Current:</span><span id=\"stat-curr-ram\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Average:</span><span id=\"stat-avg-ram\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Lowest:</span><span id=\"stat-min-ram\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Peak:</span><span id=\"stat-max-ram\" class=\"stat-val\">--</span></div>\n                    </div>\n                    <div class=\"stat-group\">\n                        <div class=\"stat-group-title\">💾 SSD/HDD</div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Current:</span><span id=\"stat-curr-disk\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Average:</span><span id=\"stat-avg-disk\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Lowest:</span><span id=\"stat-min-disk\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Peak:</span><span id=\"stat-max-disk\" class=\"stat-val\">--</span></div>\n                    </div>\n                </div>\n            </div>\n            \n            <div id=\"sub-view-world\" class=\"chart-sub-container\">\n                <div class=\"grid\" style=\"grid-template-columns: repeat(2, 1fr);\">\n                    <div class=\"card\"><div class=\"card-header\">Entities & Chunks</div><div style=\"height: 300px;\"><canvas id=\"worldChart\"></canvas></div></div>\n                    <div class=\"card\">\n                        <div class=\"card-header\">⚠️ Top 5 Worst Chunks (Live)</div>\n                        <table class=\"chunk-table\">\n                            <thead><tr><th>Location (World [X, Z])</th><th>Entity Count</th></tr></thead>\n                            <tbody id=\"chunk-list\"><tr><td colspan=\"2\">Loading...</td></tr></tbody>\n                        </table>\n                    </div>\n                </div>\n                <div class=\"grid\" style=\"grid-template-columns: repeat(2, 1fr); margin-top: 1rem;\">\n                    <div class=\"stat-group\">\n                        <div class=\"stat-group-title\">🧟 Entities</div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Current:</span><span id=\"stat-curr-ent\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Average:</span><span id=\"stat-avg-ent\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Lowest:</span><span id=\"stat-min-ent\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Peak:</span><span id=\"stat-max-ent\" class=\"stat-val\">--</span></div>\n                    </div>\n                    <div class=\"stat-group\">\n                        <div class=\"stat-group-title\">🗺️ Chunks</div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Current:</span><span id=\"stat-curr-chu\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Average:</span><span id=\"stat-avg-chu\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Lowest:</span><span id=\"stat-min-chu\" class=\"stat-val\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Peak:</span><span id=\"stat-max-chu\" class=\"stat-val\">--</span></div>\n                    </div>\n                </div>\n            </div>\n            \n            <div id=\"sub-view-players\" class=\"chart-sub-container\">\n                <div class=\"grid\">\n                    <div class=\"card\"><div class=\"card-header\">Player Activity History (24h)</div><div style=\"height: 300px;\"><canvas id=\"playerChart\"></canvas></div></div>\n                </div>\n                <div class=\"grid\" style=\"grid-template-columns: 1fr; margin-top: 1rem;\">\n                    <div class=\"stat-group\" style=\"max-width: 500px; margin: 0 auto; width: 100%;\">\n                        <div class=\"stat-group-title\">👥 Players</div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Current Online:</span><span id=\"stat-curr-pla\" class=\"stat-val\" style=\"color: var(--accent);\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Average Online:</span><span id=\"stat-avg-pla\" class=\"stat-val\" style=\"color: var(--accent);\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Lowest Online:</span><span id=\"stat-min-pla\" class=\"stat-val\" style=\"color: var(--accent);\">--</span></div>\n                        <div class=\"stat-row\"><span class=\"stat-label\">Peak Online:</span><span id=\"stat-max-pla\" class=\"stat-val\" style=\"color: var(--accent);\">--</span></div>\n                    </div>\n                </div>\n            </div>\n        </div>\n\n        \n        <div id=\"view-playersList\" class=\"view\">\n            <div class=\"grid\" id=\"player-grid\" style=\"grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));\">\n                \n            </div>\n        </div>\n\n        \n        <div id=\"view-actions\" class=\"view\">\n            <div class=\"grid\">\n                <div class=\"card\">\n                    <div class=\"card-header\">Emergency Controls</div>\n                    <div style=\"display: flex; gap: 15px; flex-wrap: wrap;\">\n                        <button class=\"btn btn-danger\" onclick=\"postAction('panic')\">🚨 PANIC CLEAR ITEMS</button>\n                        <button class=\"btn btn-warn\" onclick=\"postAction('cmd:save-all')\">💾 FORCE SAVE-ALL</button>\n                        <button class=\"btn btn-primary\" onclick=\"postAction('cmd:gc')\">🧹 RUN GC (Garbage Collector)</button>\n                    </div>\n                </div>\n            </div>\n        </div>\n    </main>\n\n    <script>\n        function switchTab(t) { document.querySelectorAll('.view, .nav-item').forEach(e => e.classList.remove('active')); document.getElementById('view-'+t).classList.add('active'); document.getElementById('nav-'+t).classList.add('active'); if(t==='charts') switchSubTab('perf'); }\n        function switchSubTab(t) { document.querySelectorAll('.chart-sub-container, .sub-tab').forEach(e => e.classList.remove('active')); document.getElementById('sub-view-'+t).classList.add('active'); document.getElementById('sub-tab-'+t).classList.add('active'); }\n        \n        function postAction(act) { fetch('/api/action', { method:'POST', body:act }).then(() => alert('Action sent!')); }\n\n        Chart.defaults.color = '#94a3b8'; \n        Chart.defaults.borderColor = '#334155';\n        const commonOptions = { maintainAspectRatio: false, responsive: true, animation: false, interaction: { mode: 'index', intersect: false }, elements: { line: { tension: 0.3 } } };\n        const pointConfig = { pointRadius: 0, pointHoverRadius: 4, borderWidth: 1.5 };\n        const perfChart = new Chart(document.getElementById('perfChart').getContext('2d'), { type: 'line', data: { labels: [], datasets: [ { label: 'TPS', borderColor: '#10b981', data: [], yAxisID: 'y', ...pointConfig }, { label: 'MSPT (ms)', borderColor: '#f59e0b', data: [], yAxisID: 'y1', ...pointConfig } ]}, options: { ...commonOptions, scales: { y: { position: 'left', max: 20 }, y1: { position: 'right', min: 0, grid: { drawOnChartArea: false } } } } });\n        const sysChart = new Chart(document.getElementById('sysChart').getContext('2d'), { type: 'line', data: { labels: [], datasets: [ { label: 'CPU Usage (%)', borderColor: '#3b82f6', backgroundColor: 'rgba(59, 130, 246, 0.1)', fill: true, data: [], ...pointConfig }, { label: 'RAM Usage (%)', borderColor: '#8b5cf6', backgroundColor: 'rgba(139, 92, 246, 0.1)', fill: true, data: [], ...pointConfig } ]}, options: { ...commonOptions, scales: { y: { min: 0, max: 100 } } } });\n        const diskChart = new Chart(document.getElementById('diskChart').getContext('2d'), { type: 'line', data: { labels: [], datasets: [ { label: 'Disk Usage (%)', borderColor: '#ec4899', backgroundColor: 'rgba(236, 72, 153, 0.1)', fill: true, data: [], ...pointConfig } ]}, options: { ...commonOptions, scales: { y: { min: 0, max: 100 } } } });\n        const worldChart = new Chart(document.getElementById('worldChart').getContext('2d'), { type: 'line', data: { labels: [], datasets: [ { label: 'Entities', borderColor: '#ef4444', data: [], yAxisID: 'y', ...pointConfig }, { label: 'Chunks', borderColor: '#eab308', data: [], yAxisID: 'y1', ...pointConfig } ]}, options: { ...commonOptions, scales: { y: { position: 'left', min: 0 }, y1: { position: 'right', min: 0, grid: { drawOnChartArea: false } } } } });\n        const playerChart = new Chart(document.getElementById('playerChart').getContext('2d'), { type: 'line', data: { labels: [], datasets: [ { label: 'Online Players', borderColor: '#14b8a6', backgroundColor: 'rgba(20, 184, 166, 0.1)', fill: true, data: [], ...pointConfig } ]}, options: { ...commonOptions, scales: { y: { min: 0, suggestedMax: 20, ticks: { stepSize: 1 } } } } });\n\n        function getColorClass(val, warn, bad, rev) { return rev ? (val<=bad?'val-bad':val<=warn?'val-warn':'val-good') : (val>=bad?'val-bad':val>=warn?'val-warn':'val-good'); }\n        function getArrStats(arr) { if(!arr || arr.length === 0) return { min: 0, max: 0, avg: 0 }; let min = Math.min(...arr); let max = Math.max(...arr); let sum = arr.reduce((a, b) => a + b, 0); return { min: min, max: max, avg: (sum / arr.length) }; }\n\n        function fetchLiveStats() {\n            fetch('/api/stats').then(res => res.json()).then(d => {\n                document.getElementById('val-tps').innerText = d.tps.toFixed(2); document.getElementById('val-tps').className = 'card-value ' + getColorClass(d.tps, 18, 14, true);\n                document.getElementById('val-mspt').innerText = d.mspt.toFixed(1); document.getElementById('val-mspt').className = 'card-value ' + getColorClass(d.mspt, 40, 50, false);\n                document.getElementById('val-cpu').innerText = d.cpu.toFixed(1)+'%'; document.getElementById('val-ram').innerText = d.ram.toFixed(1)+'%'; document.getElementById('val-disk').innerText = d.disk.toFixed(1)+'%';\n                document.getElementById('val-stress').innerText = d.stress.toFixed(1)+'%'; document.getElementById('val-chunks').innerText = d.chunks; document.getElementById('val-entities').innerText = d.entities;\n                document.getElementById('val-players').innerText = d.players + ' / ' + d.max_players;\n                document.getElementById('status-banner').className = 'status-banner ' + d.status; document.getElementById('status-banner').innerText = 'STATUS: ' + d.status + ' | PLAYERS: ' + d.players;\n                \n                document.getElementById('stat-curr-tps').innerText = d.tps.toFixed(2); document.getElementById('stat-curr-tps').className = 'stat-val ' + getColorClass(d.tps, 18.0, 14.0, true);\n                document.getElementById('stat-curr-mspt').innerText = d.mspt.toFixed(1) + ' ms'; document.getElementById('stat-curr-mspt').className = 'stat-val ' + getColorClass(d.mspt, 40.0, 50.0, false);\n                document.getElementById('stat-curr-cpu').innerText = d.cpu.toFixed(1) + '%'; document.getElementById('stat-curr-cpu').className = 'stat-val ' + getColorClass(d.cpu, 70.0, 90.0, false);\n                document.getElementById('stat-curr-ram').innerText = d.ram.toFixed(1) + '%'; document.getElementById('stat-curr-disk').innerText = d.disk.toFixed(1) + '%';\n                document.getElementById('stat-curr-ent').innerText = d.entities; document.getElementById('stat-curr-chu').innerText = d.chunks; document.getElementById('stat-curr-pla').innerText = d.players;\n                \n                let chtml = ''; d.worst_chunks.forEach(c => { chtml += `<tr><td>${c.loc}</td><td><strong style=\"color:var(--danger)\">${c.count}</strong></td></tr>`; });\n                document.getElementById('chunk-list').innerHTML = chtml || '<tr><td colspan=\"2\">Server is completely clear!</td></tr>';\n            }).catch(() => { window.location.reload(); });\n        }\n        function fetchHistory() {\n            fetch('/api/history').then(res => res.json()).then(d => {\n                if(!d.labels) return;\n                perfChart.data.labels = d.labels; perfChart.data.datasets[0].data = d.tps; perfChart.data.datasets[1].data = d.mspt; perfChart.update();\n                sysChart.data.labels = d.labels; sysChart.data.datasets[0].data = d.cpu; sysChart.data.datasets[1].data = d.ram; sysChart.update();\n                diskChart.data.labels = d.labels; diskChart.data.datasets[0].data = d.disk; diskChart.update();\n                worldChart.data.labels = d.labels; worldChart.data.datasets[0].data = d.entities; worldChart.data.datasets[1].data = d.chunks; worldChart.update();\n                playerChart.data.labels = d.labels; playerChart.data.datasets[0].data = d.players; playerChart.update();\n                \n                let tpsStats = getArrStats(d.tps); let msptStats = getArrStats(d.mspt); let cpuStats = getArrStats(d.cpu); let ramStats = getArrStats(d.ram); let diskStats = getArrStats(d.disk);\n                let entStats = getArrStats(d.entities); let chuStats = getArrStats(d.chunks); let plaStats = getArrStats(d.players);\n                \n                document.getElementById('stat-avg-tps').innerText = tpsStats.avg.toFixed(2); document.getElementById('stat-avg-tps').className = 'stat-val ' + getColorClass(tpsStats.avg, 18, 14, true);\n                document.getElementById('stat-min-tps').innerText = tpsStats.min.toFixed(2); document.getElementById('stat-min-tps').className = 'stat-val ' + getColorClass(tpsStats.min, 18, 14, true);\n                document.getElementById('stat-max-tps').innerText = tpsStats.max.toFixed(2); document.getElementById('stat-max-tps').className = 'stat-val ' + getColorClass(tpsStats.max, 18, 14, true);\n                document.getElementById('stat-avg-mspt').innerText = msptStats.avg.toFixed(1) + ' ms'; document.getElementById('stat-avg-mspt').className = 'stat-val ' + getColorClass(msptStats.avg, 40, 50, false);\n                document.getElementById('stat-min-mspt').innerText = msptStats.min.toFixed(1) + ' ms'; document.getElementById('stat-max-mspt').innerText = msptStats.max.toFixed(1) + ' ms';\n                document.getElementById('stat-avg-cpu').innerText = cpuStats.avg.toFixed(1) + '%'; document.getElementById('stat-min-cpu').innerText = cpuStats.min.toFixed(1) + '%'; document.getElementById('stat-max-cpu').innerText = cpuStats.max.toFixed(1) + '%';\n                document.getElementById('stat-avg-ram').innerText = ramStats.avg.toFixed(1) + '%'; document.getElementById('stat-min-ram').innerText = ramStats.min.toFixed(1) + '%'; document.getElementById('stat-max-ram').innerText = ramStats.max.toFixed(1) + '%';\n                document.getElementById('stat-avg-disk').innerText = diskStats.avg.toFixed(1) + '%'; document.getElementById('stat-min-disk').innerText = diskStats.min.toFixed(1) + '%'; document.getElementById('stat-max-disk').innerText = diskStats.max.toFixed(1) + '%';\n                document.getElementById('stat-avg-ent').innerText = Math.round(entStats.avg); document.getElementById('stat-min-ent').innerText = Math.round(entStats.min); document.getElementById('stat-max-ent').innerText = Math.round(entStats.max);\n                document.getElementById('stat-avg-chu').innerText = Math.round(chuStats.avg); document.getElementById('stat-min-chu').innerText = Math.round(chuStats.min); document.getElementById('stat-max-chu').innerText = Math.round(chuStats.max);\n                document.getElementById('stat-avg-pla').innerText = Math.round(plaStats.avg); document.getElementById('stat-min-pla').innerText = Math.round(plaStats.min); document.getElementById('stat-max-pla').innerText = Math.round(plaStats.max);\n            });\n        }\n        function fetchPlayers() {\n            if(!document.getElementById('view-playersList').classList.contains('active')) return;\n            fetch('/api/players').then(res => res.json()).then(d => {\n                let html = '';\n                d.forEach(p => {\n                    let pingCol = p.ping < 50 ? '#10b981' : (p.ping < 120 ? '#f59e0b' : '#ef4444');\n                    html += `<div class=\"player-card\"><div class=\"player-info\"><img class=\"player-head\" src=\"https://minotar.net/helm/${p.uuid}/40.png\"><div><div style=\"font-weight:bold\">${p.name}</div><div style=\"font-size:0.8rem;color:${pingCol}\">${p.ping} ms</div></div></div><button class=\"btn btn-danger\" style=\"padding:0.5rem 1rem\" onclick=\"postAction('kick:${p.name}')\">Kick</button></div>`;\n                });\n                document.getElementById('player-grid').innerHTML = html || '<div style=\"color:var(--text-muted)\">No players online.</div>';\n            });\n        }\n        \n        setInterval(fetchLiveStats, 1000); fetchLiveStats();\n        setInterval(fetchHistory, 60000); fetchHistory();\n        setInterval(fetchPlayers, 2000);\n    </script>\n</body>\n</html>";
/*     */     } 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */     
/* 554 */     paramHttpExchange.getResponseHeaders().add("Content-Type", "text/html; charset=UTF-8");
/* 555 */     byte[] arrayOfByte = str.getBytes(StandardCharsets.UTF_8);
/* 556 */     paramHttpExchange.sendResponseHeaders(200, arrayOfByte.length);
/* 557 */     OutputStream outputStream = paramHttpExchange.getResponseBody();
/* 558 */     outputStream.write(arrayOfByte);
/* 559 */     outputStream.close();
/*     */   }
/*     */ }


/* Location:              C:\Users\IK\Videos\Server-Ai-Optimizer-2.5.jar!\org\nyxiikcz\aioptimizer\systems\WebServerManager$RootHandler.class
 * Java compiler version: 21 (65.0)
 * JD-Core Version:       1.1.3
 */